// Project Euler
// Problem #2
//
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

var current = 2;
var last = 1;
var sum = 0; 
var temp; 

while (current < 4000000) {
	if (!(current % 2)){
		sum += current;
	};
	temp = current;
	current += last;
	last = temp;
};

console.log(sum);

// Solution: 4613732